import "@/_app/styles";
import { LayoutProps } from "@/_app/config/type";
import { Nav } from "@/widgets/nav";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="ko">
      <body className="h-dvh w-dvw">
        <div className="m-auto flex h-dvh max-w-[1137px] bg-zinc-100">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
